/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/scene.glb -o src/components/Scene.tsx -r public --types --draco 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    wire_01: THREE.Mesh
    wire_02: THREE.Mesh
    wire_03: THREE.Mesh
    wire_04: THREE.Mesh
    wire_05: THREE.Mesh
    wire_06: THREE.Mesh
    wire_07: THREE.Mesh
    light_body: THREE.Mesh
    light_bulb: THREE.Mesh
    light_hook_01: THREE.Mesh
    light_hook_02: THREE.Mesh
    light_joint_01: THREE.Mesh
    light_joint_02: THREE.Mesh
    light_wire_01: THREE.Mesh
    light_wire_02: THREE.Mesh
    screen: THREE.Mesh
    floor: THREE.Mesh
    ceil_frame: THREE.Mesh
    ceil_upper: THREE.Mesh
    screen_cable: THREE.Mesh
    speaker: THREE.Mesh
  }
  materials: {
    cable: THREE.MeshStandardMaterial
    T_hanging_lights_1001: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
    floor: THREE.MeshStandardMaterial
    ceil_frame: THREE.MeshStandardMaterial
    ceil: THREE.MeshStandardMaterial
    cable_screen: THREE.MeshStandardMaterial
    floor_speaker_1001: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>
>

export function MOdel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/scene.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[0, 31.745, 0]}>
        <mesh
          geometry={nodes.wire_01.geometry}
          material={materials.cable}
          position={[20.579, -1.313, -12.122]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.741}
        />
        <mesh
          geometry={nodes.wire_02.geometry}
          material={materials.cable}
          position={[-6.661, -1.313, -81.207]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.741}
        />
        <mesh
          geometry={nodes.wire_03.geometry}
          material={materials.cable}
          position={[-23.972, -1.313, -43.013]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.741}
        />
        <mesh
          geometry={nodes.wire_04.geometry}
          material={materials.cable}
          position={[15.808, -1.361, -57.061]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.539}
        />
        <mesh
          geometry={nodes.wire_05.geometry}
          material={materials.cable}
          position={[2.974, -1.685, -9.501]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.539}
        />
        <mesh
          geometry={nodes.wire_06.geometry}
          material={materials.cable}
          position={[-36.804, -1.361, -42.163]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.539}
        />
        <mesh
          geometry={nodes.wire_07.geometry}
          material={materials.cable}
          position={[47.701, -1.361, -40.549]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.539}
        />
      </group>
      <group
        position={[0.021, 32.744, 11.615]}
        rotation={[0, Math.PI / 2, 0]}
        scale={1.801}
      >
        <mesh
          geometry={nodes.light_body.geometry}
          material={materials.T_hanging_lights_1001}
          position={[-0.194, -3.216, 0.118]}
        />
        <mesh
          geometry={nodes.light_bulb.geometry}
          material={materials.T_hanging_lights_1001}
          position={[-0.194, -3.452, 0.118]}
        />
        <mesh
          geometry={nodes.light_hook_01.geometry}
          material={materials.T_hanging_lights_1001}
          position={[-0.193, -2.409, -5.793]}
        />
        <mesh
          geometry={nodes.light_hook_02.geometry}
          material={materials.T_hanging_lights_1001}
          position={[-0.266, -2.43, 5.793]}
        />
        <mesh
          geometry={nodes.light_joint_01.geometry}
          material={materials.T_hanging_lights_1001}
          position={[-0.194, -1.974, -5.793]}
        />
        <mesh
          geometry={nodes.light_joint_02.geometry}
          material={materials.T_hanging_lights_1001}
          position={[-0.266, -1.993, 5.793]}
        />
        <mesh
          geometry={nodes.light_wire_01.geometry}
          material={materials.T_hanging_lights_1001}
          position={[-0.192, 2.196, -5.792]}
        />
        <mesh
          geometry={nodes.light_wire_02.geometry}
          material={materials.T_hanging_lights_1001}
          position={[-0.265, 2.176, 5.794]}
        />
      </group>
      <mesh
        geometry={nodes.screen.geometry}
        material={materials.screen}
        position={[0, 15.195, 0]}
      />
      <mesh
        geometry={nodes.floor.geometry}
        material={materials.floor}
        scale={[67.234, 0.672, 67.234]}
      />
      <mesh
        geometry={nodes.ceil_frame.geometry}
        material={materials.ceil_frame}
        position={[0, 30.306, 0]}
        scale={[67.234, 0.672, 67.234]}
      />
      <mesh
        geometry={nodes.ceil_upper.geometry}
        material={materials.ceil}
        position={[0, 32.121, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={[67.234, 0.672, 67.234]}
      />
      <mesh
        geometry={nodes.screen_cable.geometry}
        material={materials.cable_screen}
        position={[15.748, 29.47, -0.087]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-0.051, -9.483, -0.051]}
      />
      <mesh
        geometry={nodes.speaker.geometry}
        material={materials.floor_speaker_1001}
        position={[18.729, 1.739, 1.265]}
        rotation={[0, 0.971, 0]}
        scale={0.059}
      />
    </group>
  )
}

useGLTF.preload('/models/scene.glb')
